source 'https://github.com/CocoaPods/Specs.git'
# platform :ios, '6.0'
use_frameworks!

target 'PCOS' do
    pod 'SwiftOverlays', '~> 0.11'    
    pod "SwiftyJSON", ">= 2.2"
    pod 'Alamofire', '~> 1.2'
    pod "TSMessages"
end

target 'PCOSTests' do

end

